export const ACTIONS_ID = {
  CANCEL_COMPUTE_MIGRATION: 'vm-action-cancel-migrate',
  CLONE: 'vm-action-clone',
  CONTROL_MENU: 'control-menu',
  COPY_SSH_COMMAND: 'vm-action-copy-ssh',
  DELETE: 'vm-action-delete',
  EDIT_LABELS: 'vm-action-edit-labels',
  EDIT_RUN_STRATEGY: 'vm-action-change-run-strategy',
  FORCE_STOP: 'vm-action-force-stop',
  MIGRATE_COMPUTE: 'vm-action-migrate-compute',
  MIGRATE_STORAGE: 'vm-action-migrate-storage',
  MIGRATION_MENU: 'migration-menu',
  MOVE_TO_FOLDER: 'vm-action-move-to-folder',
  OPEN_CONSOLE: 'vm-action-open-console',
  PAUSE: 'vm-action-pause',
  RESET: 'vm-action-reset',
  RESTART: 'vm-action-restart',
  SAVE_AS_TEMPLATE: 'vm-action-save-as-template',
  SNAPSHOT: 'vm-action-snapshot',
  START: 'vm-action-start',
  STOP: 'vm-action-stop',
  UNPAUSE: 'vm-action-unpause',
} as const;
