export const ACTIONS_ID = {
  BULK_MIGRATE_COMPUTE: 'vm-action-migrate-compute',
  BULK_MIGRATE_STORAGE: 'vm-action-migrate-storage',
  DELETE: 'vm-action-delete',
  EDIT_LABELS: 'vm-action-edit-labels',
  EDIT_RUN_STRATEGY: 'vm-action-change-run-strategy',
  MOVE_TO_FOLDER: 'vm-action-move-to-folder',
  PAUSE: 'vm-action-pause',
  RESET: 'vm-action-reset',
  RESTART: 'vm-action-restart',
  SNAPSHOT: 'vm-action-snapshot',
  START: 'vm-action-start',
  STOP: 'vm-action-stop',
  UNPAUSE: 'vm-action-unpause',
} as const;
