/** Segment event property values — use these instead of inline strings. */

export const TELEMETRY_HELP_ITEM_ID = {
  HELP_ICON: 'help-icon',
} as const;

export const TELEMETRY_TASK_TYPE = {
  VM_CREATION: 'vm_creation',
} as const;

export const TELEMETRY_TASK_ERROR_TYPE = {
  VM_CREATION_FAILED: 'vm_creation_failed',
} as const;

export const TELEMETRY_VM_CREATION_METHOD = {
  CLONE: 'clone',
  INSTANCE_TYPE: 'instancetype',
  SCRATCH: 'scratch',
  TEMPLATE: 'template',
} as const;

export const TELEMETRY_TEMPLATE_TYPE = {
  PREDEFINED: 'predefined',
  USER_DEFINED: 'user_defined',
} as const;

export const TELEMETRY_VM_ACTION = {
  CLONE: 'clone',
  DELETE: 'delete',
  MIGRATE: 'migrate',
  PAUSE: 'pause',
  RESET: 'reset',
  RESTART: 'restart',
  SNAPSHOT: 'snapshot',
  START: 'start',
  STOP: 'stop',
  UNPAUSE: 'unpause',
} as const;

export {
  MTV_PROVIDER_TYPE,
  TELEMETRY_ALERT_ACTION,
  TELEMETRY_ALERT_SEVERITY,
  TELEMETRY_CONSOLE_ACTION,
  TELEMETRY_CONSOLE_SESSION_TYPE,
  TELEMETRY_CONSOLE_TYPE,
  TELEMETRY_DISK_TYPE,
  TELEMETRY_EDITOR_VIEW_SWITCH,
  TELEMETRY_ERROR_RESOLUTION_ACTION,
  TELEMETRY_EXTERNAL_MONITORING_TOOL,
  TELEMETRY_GPU_PASSTHROUGH_TYPE,
  TELEMETRY_HOTPLUG_OPERATION,
  TELEMETRY_OS_FAMILY,
  TELEMETRY_PROFICIENCY_LEVEL,
  TELEMETRY_PROFICIENCY_MILESTONE,
  TELEMETRY_PROJECT_MAPPING_METHOD,
  TELEMETRY_RESOURCE_CREATION_METHOD,
  TELEMETRY_RESOURCE_TYPE,
  TELEMETRY_SORT_ORDER,
  TELEMETRY_SOURCE_PROVIDER,
  TELEMETRY_STATUS,
  TELEMETRY_TREE_VIEW_ACTION,
  TELEMETRY_UNKNOWN_ERROR_MESSAGE,
  TELEMETRY_VM_DETAIL_TAB,
  TELEMETRY_VM_ERROR_TYPE,
  TELEMETRY_VM_STATE,
  TELEMETRY_WORKLOAD_TYPE,
} from './telemetry-event-constants';
