import './e2e/a-setup.cy.ts';
import './e2e/overview.cy.ts';
import './e2e/check-tab-yaml.cy.ts';
import './e2e/catalog-filter.cy.ts';
import './e2e/create-vm.cy.ts';
import './e2e/it-vm.cy.ts';
import './e2e/networking.cy.ts';
import './e2e/template-list.cy.ts';
import './e2e/set-default-sc.cy.ts';
// import './e2e/catalog-create.cy.ts';
