export enum VirtualMachineDetailsTab {
  Configurations = 'configuration',
  Console = 'console',
  Details = 'details',
  Diagnostics = 'diagnostics',
  Environment = 'environment',
  Events = 'events',
  InitialRun = 'initial',
  Logs = 'logs',
  Metadata = 'metadata',
  Metrics = 'metrics',
  Network = 'network',
  Overview = '',
  Scheduling = 'scheduling',
  Snapshots = 'snapshots',
  SSH = 'ssh',
  Storage = 'storage',
  Tables = 'tables',
  YAML = 'yaml',
}

export const VirtualMachineConfigurationTabInner = new Set([
  VirtualMachineDetailsTab.Details,
  VirtualMachineDetailsTab.Metadata,
  VirtualMachineDetailsTab.Network,
  VirtualMachineDetailsTab.Scheduling,
  VirtualMachineDetailsTab.SSH,
  VirtualMachineDetailsTab.Storage,
  VirtualMachineDetailsTab.InitialRun,
]);

export const VirtualMachineDetailsTabLabel: Partial<Record<VirtualMachineDetailsTab, string>> = {
  [VirtualMachineDetailsTab.Configurations]: 'Configuration',
  [VirtualMachineDetailsTab.Console]: 'Console',
  [VirtualMachineDetailsTab.Details]: 'Details',
  [VirtualMachineDetailsTab.Diagnostics]: 'Diagnostics',
  [VirtualMachineDetailsTab.Environment]: 'Environment',
  [VirtualMachineDetailsTab.Events]: 'Events',
  [VirtualMachineDetailsTab.InitialRun]: 'Initial run',
  [VirtualMachineDetailsTab.Metadata]: 'Metadata',
  [VirtualMachineDetailsTab.Metrics]: 'Metrics',
  [VirtualMachineDetailsTab.Network]: 'Network',
  [VirtualMachineDetailsTab.Overview]: 'Overview',
  [VirtualMachineDetailsTab.Scheduling]: 'Scheduling',
  [VirtualMachineDetailsTab.Snapshots]: 'Snapshots',
  [VirtualMachineDetailsTab.SSH]: 'SSH',
  [VirtualMachineDetailsTab.Storage]: 'Storage',
  [VirtualMachineDetailsTab.YAML]: 'YAML',
};
