{{- if .Values.console.pluginProxy.endpoint }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ci-test-stack.consoleName" . }}-config
  labels:
    {{- include "ci-test-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
data:
  pluginProxy: |
    {
      "services": [
        {
          "consoleAPIPath": "/api/proxy/plugin/kubevirt-plugin/kubevirt-apiserver-proxy/",
          "endpoint": {{ .Values.console.pluginProxy.endpoint | quote }},
          "authorize": true
        }
      ]
    }
{{- end }}
