export const diskReducerActions = Object.freeze({
  SET_DISK_MAME: 'setDiskName',
  SET_DISK_SOURCE: 'setDiskSource',
  SET_DISK_SIZE: 'setDiskSize',
  SET_DISK_TYPE: 'setDiskType',
  SET_DETACH_HOTPLUG: 'setDetachHotplug',
  SET_DISK_INTERFACE: 'setDiskInterface',
  SET_STORAGE_CLASS: 'setStorageClass',
  SET_APPLY_STORAGE_PROFILE_SETTINGS: 'setApplyStorageProfileSettings',
  SET_STORAGE_PROFILE_SETTINGS_CHECKBOX_DISABLED: 'setStorageProfileSettingsCheckboxDisabled',
  SET_ACCESS_MODE: 'setAccessMode',
  SET_VOLUME_MODE: 'setVolumeMode',
  SET_STORAGE_CLASS_PROVISIONER: 'setStorageClassProvisioner',
  SET_ENABLE_PREALLOCATION: 'setEnablePreallocation',
});
