FROM node:16 AS builder
WORKDIR /app
COPY . /app
RUN yarn install && yarn build


FROM cypress/browsers:node14.17.0-chrome91-ff89 as serverpackage
RUN yarn global add http-server
RUN export PATH="$(yarn global bin):$PATH"

FROM serverpackage
COPY --from=builder /app/dist /app
COPY --from=builder /app/dist /app/compatibility
COPY --from=builder /app/http-server.sh .
ENTRYPOINT [ "./http-server.sh", "./app" ]