import * as path from 'path';

import { ConsoleRemotePlugin } from '@openshift-console/dynamic-plugin-sdk-webpack';
import { Configuration, CopyRspackPlugin, DefinePlugin, ProvidePlugin } from '@rspack/core';
import { TsCheckerRspackPlugin } from 'ts-checker-rspack-plugin';

import extensions from './plugin-extensions';
import pluginMetadata from './plugin-metadata';

const isProd = process.env.NODE_ENV === 'production';

const KUBEVIRT_PLUGIN_PORT = process.env.PORT || process.env.KUBEVIRT_PLUGIN_PORT || 9001;

const config: Configuration = {
  context: path.resolve(__dirname, 'src'),
  devServer: {
    // Allow bridge running in a container to connect to the plugin dev server.
    allowedHosts: 'all',
    client: {
      progress: true,
      webSocketURL: {
        port: KUBEVIRT_PLUGIN_PORT,
      },
    },
    devMiddleware: {
      writeToDisk: true,
    },
    headers: {
      'Access-Control-Allow-Headers': 'X-Requested-With, Content-Type, Authorization',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': 'no-store',
    },
    hot: true,
    port: KUBEVIRT_PLUGIN_PORT,
    static: {
      directory: path.join(__dirname, 'dist'),
    },
  },
  devtool: isProd ? false : 'source-map',
  entry: {}, // Plugin entry script is generated by ConsoleRemotePlugin
  mode: isProd ? 'production' : 'development',
  module: {
    rules: [
      {
        exclude: /\/node_modules\//,
        test: /\.(jsx?|tsx?)$/,
        use: {
          loader: 'builtin:swc-loader',
          options: {
            detectSyntax: 'auto',
            jsc: {
              target: 'es2021',
              transform: {
                react: {
                  development: !isProd,
                  runtime: 'automatic',
                },
              },
            },
            sourceMaps: true,
          },
        },
        type: 'javascript/auto',
      },
      {
        exclude:
          /node_modules\/(?!(@patternfly|@openshift-console\/plugin-shared|@openshift-console\/dynamic-plugin-sdk)\/).*/,
        test: /\.scss$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          },
          {
            loader: 'resolve-url-loader',
            options: {
              sourceMap: true,
            },
          },
          {
            loader: 'sass-loader',
            options: {
              api: 'modern',
              sassOptions: {
                style: isProd ? 'compressed' : 'expanded',
              },
              sourceMap: true,
            },
          },
        ],
        type: 'javascript/auto',
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
        type: 'javascript/auto',
      },
      {
        test: /\.(png|jpg|jpeg|gif|svg|woff2?|ttf|eot|otf)(\?.*$|$)/,
        type: 'asset/resource',
        generator: {
          filename: isProd ? 'assets/[contenthash][ext]' : 'assets/[name]-[contenthash][ext]',
        },
      },
      {
        test: /\.m?js/,
        resolve: {
          fullySpecified: false,
        },
      },
    ],
  },
  optimization: {
    chunkIds: isProd ? 'deterministic' : 'named',
    minimize: isProd,
  },
  output: {
    chunkFilename: isProd ? '[name]-chunk-[chunkhash].min.js' : '[name]-chunk.js',
    filename: isProd ? '[name]-bundle-[chunkhash].min.js' : '[name]-bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new CopyRspackPlugin({
      patterns: [{ from: '../locales', to: '../dist/locales' }],
    }),
    new ConsoleRemotePlugin({
      extensions,
      pluginMetadata,
      sharedDynamicModuleSettings: {
        moduleFilter: (moduleRequest) => {
          const isCode = /\.(jsx?|tsx?)$/.test(moduleRequest);
          const isVendor = moduleRequest.includes('/node_modules/');

          return (
            isCode &&
            (!isVendor ||
              moduleRequest.includes('/node_modules/@openshift-console/') ||
              moduleRequest.includes('/node_modules/@patternfly/react-data-view/'))
          );
        },
      },
    }),
    new TsCheckerRspackPlugin({
      typescript: {
        configFile: path.resolve(__dirname, 'tsconfig.json'),
        diagnosticOptions: {
          semantic: true,
          syntactic: true,
        },
        memoryLimit: 4096,
      },
    }),
    new ProvidePlugin({
      process: 'process/browser',
    }),
    new DefinePlugin({
      'process.env': JSON.stringify({ NODE_ENV: process.env.NODE_ENV }),
      'process.env.OLS_API_BASE_URL': JSON.stringify({
        OLS_API_BASE_URL: process.env.OLS_API_BASE_URL,
      }),
    }),
  ],
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
    modules: [path.join(__dirname, 'node_modules')],
    tsConfig: path.resolve(__dirname, 'tsconfig.json'),
  },
  watchOptions: {
    ignored: '**/node_modules',
  },
};

export default config;
