export const FLAG_KUBEVIRT_DYNAMIC = 'KUBEVIRT_DYNAMIC';
export const FLAG_KUBEVIRT_CDI = 'KUBEVIRT_CDI';
export const FLAG_CONSOLE_CLI_DOWNLOAD = 'CONSOLE_CLI_DOWNLOAD';
export const FLAG_KUBEVIRT_PREFERENCES = 'KUBEVIRT_PREFERENCES';
export const FLAG_KUBEVIRT_INSTANCETYPES = 'KUBEVIRT_INSTANCETYPES';
