export const FLAG_KUBEVIRT_DYNAMIC = 'KUBEVIRT_DYNAMIC';
export const FLAG_KUBEVIRT_CDI = 'KUBEVIRT_CDI';
export const FLAG_CONSOLE_CLI_DOWNLOAD = 'CONSOLE_CLI_DOWNLOAD';
export const FLAG_KUBEVIRT_PREFERENCES = 'KUBEVIRT_PREFERENCES';
export const FLAG_KUBEVIRT_INSTANCETYPES = 'KUBEVIRT_INSTANCETYPES';
export const FLAG_KUBEVIRT_QUOTAS = 'KUBEVIRT_QUOTAS';

export const FLAG_SHOW_MIGRATION_SECTION = 'SHOW_MIGRATION_SECTION';

export const FLAG_NMSTATE_DYNAMIC = 'NMSTATE_DYNAMIC';
export const FLAG_LIGHTSPEED_PLUGIN = 'LIGHTSPEED_PLUGIN';

/** When true, show the Virtualization perspective and admin Virtualization nav section (CNV-81682). */
export const FLAG_KUBEVIRT_VIRTUALIZATION_NAV = 'KUBEVIRT_VIRTUALIZATION_NAV';

export const MIGRATION_SECTION_ID = 'migration';
export const KUBEVIRT_PLUGIN_NAME = 'kubevirt-plugin';
