apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-env-controller-script
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ci-env-controller.labels" . | nindent 4 }}
data:
  ci-env-controller.sh: |
    {{- .Files.Get "scripts/ci-env-controller.sh" | nindent 4 }}
