export enum VM_STATUS {
  CrashLoopBackOff = 'CrashLoopBackOff',
  DataVolumeError = 'DataVolumeError',
  Deleting = 'Deleting',
  ErrImagePull = 'ErrImagePull',
  ErrorDataVolumeNotFound = 'ErrorDataVolumeNotFound',
  ErrorPvcNotFound = 'ErrorPvcNotFound',
  ErrorUnschedulable = 'ErrorUnschedulable',
  ImagePullBackOff = 'ImagePullBackOff',
  Migrating = 'Migrating',
  Paused = 'Paused',
  Provisioning = 'Provisioning',
  Running = 'Running',
  Starting = 'Starting',
  Stopped = 'Stopped',
  Stopping = 'Stopping',
  Terminating = 'Terminating',
  Unknown = 'Unknown',
  WaitingForVolumeBinding = 'WaitingForVolumeBinding',
}
