FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:16 as build
COPY --from=openshift/origin-cli:latest /usr/bin/oc /usr/local/bin/oc

RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y install --no-install-recommends \
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 xauth xvfb