/**
 * File system operations, logging, storage state, and test results directory utilities.
 */

import * as fs from 'fs';
import * as path from 'path';

import { EnvVariables } from './env-variables';

// ---------------------------------------------------------------------------
// FileUtils
// ---------------------------------------------------------------------------

export class FileUtils {
  static createDirectory(dirPath: string): void {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  static deleteFile(filePath: string): boolean {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      return true;
    }
    return false;
  }

  static exists(filePath: string): boolean {
    return fs.existsSync(filePath);
  }

  static getDirectory(filePath: string): string {
    return path.dirname(filePath);
  }

  static getFileName(filePath: string): string {
    return path.basename(filePath);
  }

  static joinPath(...segments: string[]): string {
    return path.join(...segments);
  }

  static readFile(filePath: string, encoding: BufferEncoding = 'utf-8'): string {
    return fs.readFileSync(filePath, encoding);
  }

  static readFileTrimmed(filePath: string, encoding: BufferEncoding = 'utf-8'): string {
    return fs.readFileSync(filePath, encoding).trim();
  }

  static resolvePath(...segments: string[]): string {
    return path.resolve(...segments);
  }

  static writeFile(filePath: string, content: string, encoding: BufferEncoding = 'utf-8'): void {
    fs.writeFileSync(filePath, content, encoding);
  }
}

// ---------------------------------------------------------------------------
// logger
// ---------------------------------------------------------------------------

/**
 * Simple logger utility that writes to stdout/stderr.
 * Avoids eslint console.log warnings while maintaining terminal output.
 */
export const logger = {
  info: (message: string): void => {
    process.stdout.write(`${message}\n`);
  },

  error: (message: string): void => {
    process.stderr.write(`${message}\n`);
  },

  warn: (message: string): void => {
    process.stderr.write(`⚠️  ${message}\n`);
  },

  success: (message: string): void => {
    process.stdout.write(`✅ ${message}\n`);
  },
};

// ---------------------------------------------------------------------------
// getTestResultsDir
// ---------------------------------------------------------------------------

/**
 * Returns the directory for test results output.
 *
 * - PLAYWRIGHT_OUTPUT_DIR: explicit path (absolute or relative to cwd)
 * - Default: repo-root/test-results
 *
 * @param repoRoot - Absolute path to repo root (parent of playwright/)
 */
export function getTestResultsDir(repoRoot: string): string {
  if (process.env.PLAYWRIGHT_OUTPUT_DIR) {
    const dir = process.env.PLAYWRIGHT_OUTPUT_DIR;
    return path.isAbsolute(dir) ? dir : path.resolve(process.cwd(), dir);
  }
  return path.join(repoRoot, 'test-results');
}

// ---------------------------------------------------------------------------
// getStorageStatePath
// ---------------------------------------------------------------------------

/**
 * Resolve the storage state file path generated by global.setup.ts.
 * Returns the path even if the file doesn't exist (for context creation).
 * The storage state will be applied if the file exists, otherwise context will start fresh.
 *
 * File naming:
 *   NON_PRIV=1   → nonpriv-state.json   (non-privileged session)
 *   default      → test-state.json      (kubeadmin session)
 */
export function getStorageStatePath(configDirname: string, silent = false): string | undefined {
  const storageStateDir = path.resolve(configDirname, '..', '.storage-states');

  const storageStateFileName = EnvVariables.isNonPrivUser
    ? 'nonpriv-state.json'
    : 'test-state.json';

  const storageStatePath = path.join(storageStateDir, storageStateFileName);

  if (fs.existsSync(storageStatePath)) {
    return storageStatePath;
  }

  if (!silent && !EnvVariables.isLocalhost) {
    // eslint-disable-next-line no-console
    console.warn(
      `Storage state file not found at ${storageStatePath} - contexts will start without authentication`,
    );
  }
  return undefined;
}
