import * as fs from 'fs';
import * as path from 'path';

import { EnvVariables } from './env-variables';

/**
 * Resolve the storage state file path generated by global.setup.ts.
 * Returns the path even if the file doesn't exist (for context creation).
 * The storage state will be applied if the file exists, otherwise context will start fresh.
 *
 * File naming:
 *   sharded run  → shard-N-state.json   (one per shard, admin or nonpriv)
 *   NON_PRIV=1   → nonpriv-state.json   (non-privileged session)
 *   default      → test-state.json      (kubeadmin session)
 */
export function getStorageStatePath(configDirname: string): string | undefined {
  const shardIndex = EnvVariables.shardIndex;
  const storageStateDir = path.resolve(configDirname, '..', '.storage-states');

  let storageStateFileName: string;
  if (EnvVariables.isSharded && shardIndex) {
    storageStateFileName = `shard-${shardIndex}-state.json`;
  } else if (EnvVariables.isNonPrivUser) {
    storageStateFileName = 'nonpriv-state.json';
  } else {
    storageStateFileName = 'test-state.json';
  }

  const storageStatePath = path.join(storageStateDir, storageStateFileName);

  // Return path if file exists, otherwise return undefined
  // Playwright will handle undefined gracefully (no storage state applied)
  if (fs.existsSync(storageStatePath)) {
    return storageStatePath;
  }

  // Suppress warning when sharded (expected: global setup hasn't created it yet)
  // and for localhost (storage state not needed for local development)
  if (!EnvVariables.isLocalhost && !EnvVariables.isSharded) {
    console.warn(
      `Storage state file not found at ${storageStatePath} - contexts will start without authentication`,
    );
  }
  return undefined;
}
