import * as fs from 'fs';
import * as path from 'path';

import { EnvVariables } from './env-variables';

/**
 * Resolve the storage state file path generated by global.setup.ts.
 * Returns the path even if the file doesn't exist (for context creation).
 * The storage state will be applied if the file exists, otherwise context will start fresh.
 *
 * File naming:
 *   NON_PRIV=1   → nonpriv-state.json   (non-privileged session)
 *   default      → test-state.json      (kubeadmin session)
 */
export function getStorageStatePath(configDirname: string, silent = false): string | undefined {
  const storageStateDir = path.resolve(configDirname, '..', '.storage-states');

  const storageStateFileName = EnvVariables.isNonPrivUser
    ? 'nonpriv-state.json'
    : 'test-state.json';

  const storageStatePath = path.join(storageStateDir, storageStateFileName);

  if (fs.existsSync(storageStatePath)) {
    return storageStatePath;
  }

  if (!silent && !EnvVariables.isLocalhost) {
    console.warn(
      `Storage state file not found at ${storageStatePath} - contexts will start without authentication`,
    );
  }
  return undefined;
}
