export const gettingStartedCard = '[data-test="getting-started"]';
export const gettingStartedTitle = '[data-test="title"]';
export const hideGettingStartedCardKebab = 'button.pf-v6-c-menu-toggle.pf-m-plain';
export const hideGettingStartedCardTooltip = 'button[data-test="hide"]';
export const restoreGettingStartedBtn = '[data-test="restore-getting-started"]';
export const quickStartsCard = '[data-test="card quick-start"]';
export const featureHighlightsCard = '[data-test="card feature-highlights"]';
export const relatedOperatorsCard = '[data-test="card related-operators"]';
export const detailsCard = '[data-test-id="kubevirt-overview-dashboard--details-card"]';
export const statusCard = '[data-test-id="vm-statuses-card"]';
export const VMperTemplateCard = '[data-test-id="vms-per-template-card"]';
export const activityCard = '[data-test-id="kv-activity-card"]';
export const resourceBlock = '[data-test-id="dashboard"]';
export const resourceCard = '.metric-charts-card';
export const permissionsCard = '[data-test-id="kv-overview-permissions-card"]';
export const popOverContent = '.pf-v6-c-popover__content';
export const closeBtn = '.pf-v6-c-popover__close';
export const topConsumersCard = '[data-test="kv-top-consumers-card"]';
export const migrationsCard = '[data-test="kv-monitoring-card"]';
export const modalTitle = '[data-test-id="modal-title"]';
export const cardTitleV6 = '.pf-v6-c-card__title';
export const itemTitle = '[data-test="detail-item-title"]';
export const closeButton = '[aria-label^="Close"]';
export const startButton = '[data-test="Start button"]';
export const statusItem = '.vm-statuses-card__status-item';
export const statusAccordion = '[data-test="Virtualization-health-item-icon"]';
export const netHealthItem = '[data-item-id="Networking-health-item"]';
export const netHealthIcon = '[data-test="Networking-health-item-icon"]';
export const cardActions = '.co-overview-card__actions';
export const alertsList = '.co-status-card__alerts-body';
export const successIcon = '[data-test="success-icon"]';
export const vmsLink = '[data-test="kv-inventory-card--vms"]';
export const templatesLink = '[data-test="kv-inventory-card--vm-templates"]';
export const nodesLink = '[data-test="kv-inventory-card--nodes"]';
export const networksLink = '[data-test="kv-inventory-card--nads"]';
export const ongoingTitle = '[data-test="ongoing-title"]';
export const ongoingActivity = '[data-test="activity"]';
export const recentActivity = '[data-test="activity-recent-title"]';
export const pauseButton = '[data-test="events-pause-button"]';
export const accessPopupButton = '#virtualization-overview-permissions-popover-btn';
export const taskItem = '[data-test="kv-permissions-card-task"]';
export const taskIcon = '[data-test="kv-permissions-card-icon"]';
export const amountButton = '#kv-top-consumers-card-amount-select';
export const metricsTitle = '.kv-top-consumers-card__metric-title';
export const metricsBody = '.kv-top-consumers-card__chart-list-body';
export const metricsContainer = '.kv-top-consumers-card__chart-list-container';
export const permissionsTable = '.permissions-tab--main';
export const permissionsRow = '.permissions-tab--main__row';
export const plusBtn = 'button[aria-label="Plus"]';
export const minusBtn = 'button[aria-label="Minus"]';
export const parMigrationsPerCluster = 'input[name="parallelMigrationsPerCluster"]';
export const parOutMigrationsPerNode = 'input[name="parallelOutboundMigrationsPerNode"]';
export const migrationDuration = '.kv-top-consumers-card__dropdown--duration';

// VM per resource
export const chartTypeSelect = 'button[id="overview-vms-per-resource-card"]';
export const itText = 'Show VirtualMachine per InstanceTypes';
export const resItem = '.co-resource-item__resource-name';
export const tourHeader = '.kv-tour-popover__header';
export const stepCount = '.kv-tour-popover__step-counter';
export const switchInput = 'input.pf-v6-c-switch__input';
export const switchLabel = 'label.pf-v6-c-switch';
export const welcomeCheckbox = '#welcome-modal-checkbox';
