import {
  CLUSTER_OBSERVABILITY_OPERATOR_NAME,
  DESCHEDULER_OPERATOR_NAME,
  FENCE_AGENTS_OPERATOR_NAME,
  NETOBSERV_OPERATOR_NAME,
  NMSTATE_OPERATOR_NAME,
  NODE_HEALTH_OPERATOR_NAME,
} from '@settings/tabs/ClusterTab/components/VirtualizationFeaturesSection/utils/constants';

export const MTV_OPERATOR_NAME = 'mtv-operator';
export const SANDBOXED_CONTAINERS_OPERATOR_NAME = 'sandboxed-containers-operator';
export const LOKI_OPERATOR_NAME = 'loki-operator';
export const CLUSTER_LOGGING_OPERATOR_NAME = 'cluster-logging';
export const METALLB_OPERATOR_NAME = 'metallb-operator';
export const NODE_MAINTENANCE_OPERATOR_NAME = 'node-maintenance-operator';
export const MULTICLUSTER_ENGINE_OPERATOR_NAME = 'multicluster-engine';
export const LOCAL_STORAGE_OPERATOR_NAME = 'local-storage-operator';
export const NUMA_RESOURCES_OPERATOR_NAME = 'numaresources-operator';
export const NODE_FEATURE_DISCOVERY_OPERATOR_NAME = 'node-feature-discovery';
export const OADP_OPERATOR_NAME = 'oadp-operator';

export const RECOMMENDED_OPERATOR_PACKAGE_NAMES: readonly string[] = [
  CLUSTER_LOGGING_OPERATOR_NAME,
  CLUSTER_OBSERVABILITY_OPERATOR_NAME,
  DESCHEDULER_OPERATOR_NAME,
  FENCE_AGENTS_OPERATOR_NAME,
  LOCAL_STORAGE_OPERATOR_NAME,
  LOKI_OPERATOR_NAME,
  METALLB_OPERATOR_NAME,
  MULTICLUSTER_ENGINE_OPERATOR_NAME,
  MTV_OPERATOR_NAME,
  NETOBSERV_OPERATOR_NAME,
  NMSTATE_OPERATOR_NAME,
  NODE_FEATURE_DISCOVERY_OPERATOR_NAME,
  NODE_HEALTH_OPERATOR_NAME,
  NODE_MAINTENANCE_OPERATOR_NAME,
  NUMA_RESOURCES_OPERATOR_NAME,
  OADP_OPERATOR_NAME,
  SANDBOXED_CONTAINERS_OPERATOR_NAME,
];
